### ISSUE TITLE
How to separate true positive alignments from a given SAM file

### ISSUE THREAD

**Issue by FadelBerakdar** [jaudoux/benchct#1]
In order to evaluate genes counts, we need to separate true positive alignments from false positive ones. I am wondering if there is any option i can use with BenchCT to produce true positive alignments while running it ?

**Comment by jaudoux** [comment]
Hu @FadelBerakdar,

Indeed, you can get true positive and false positive alignments in output. You have to specify the files where this information will be stored under the `files` section of a given software output.

The output format is SAM files without headers. The name given in parameter is just a base name, the full name will actually be `$true_positives_file-mapping.log`.

Here is a simple example of the config file that will produce these outputs:

```yaml
softwares:
  - name: crac-v2
    files:
      - name: crac-mapping.bam
        false_positives: crac-v2-false-positives
        true_positives: crac-v2-true-positives
```

Let me know if this solves your problem.

J.
